'use client'
import "style/global.css"


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function Providers({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
